combine_control_expr = false
condense_wildcard_suffixes = true
fn_single_line = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_strings = true
hex_literal_case = "Lower"
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
spaces_around_ranges = true
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
wrap_comments = true

