name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'frontend'
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20.5.1
      uses: actions/setup-node@v3
      with:
        node-version: 20.5.1
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: |
        npm i \
        npm run build
