name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Build
      run: |
        cd backend
        cargo build --verbose
    - name: Run tests
      run: |
        cd backend
        cargo test --verbose
    - name: Run clippy
      run: |
        cd backend
        cargo clippy --verbose -- -W clippy::pedantic -W clippy::nursery
